### ISSUE TITLE
Documention

### ISSUE THREAD

**Issue by laszukdawid** [willvousden/ptemcee#5]
Is there any link to documentation and examples of usage?

**Comment by Gabriel-p** [comment]
I guess the old emcee docs are as good as it gets for the time being?

* [Parallel-Tempering Ensemble MCMC](https://emcee.readthedocs.io/en/stable/user/pt.html)
* [The Parallel-Tempered Ensemble Sampler](https://emcee.readthedocs.io/en/stable/api.html#the-parallel-tempered-ensemble-sampler)

**Comment by willvousden** [comment]
ptemcee's been dormant for a while now (sorry!), but I'm doing some refactoring at the moment, and I plan to write some docs in the process, so keep an eye out for it.

**Comment by ljschumacher** [comment]
Some minimal documentation / tutorial would be much appreciated. I've tried using code I previously used in emcee– would this be correct?
`sampler = ptemcee.Sampler(nwalkers, ndim, my_logl, my_logp, 
                    ntemps=ntemps, loglargs=(arg1, arg2), threads=4)`

**Comment by laszukdawid** [comment]
Closing. One ticket less :)
